project:
  type: website

website:
  title: "Open ❤️ Science"
  repo-url: "https://github.com/bbartholdy/open-love-science"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: cards.qmd
        text: "Cards"
      - href: rules.qmd
        text: "Rules"
    right: 
      - icon: github
        href: https://github.com/ubvu/OpenTOScience
        aria-label: GitHub

format:
  html:
    theme: [default, theme.scss]
    #css: styles.css
    toc: true



